#!/bin/bash

# WireGuard server installer with public IP routing
# https://github.com/tbringuier/wireguard-install
#
# Fork of https://github.com/angristan/wireguard-install (MIT licence).
# Requires systemd. Tested on Debian, Ubuntu, Fedora, Rocky/Alma, Arch, openSUSE and Flatcar.
# Most of this fork was written with Claude (Anthropic) and reviewed by the maintainer.

RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

function isValidIpv4() {
	[[ $1 =~ ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]
}

function isValidIpv6() {
	# Hex groups separated by colons, with at most one "::" shortcut
	[[ $1 =~ ^([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}$ ]] && [[ $1 != *:::* ]] && [[ $(echo "$1" | grep -o '::' | wc -l) -le 1 ]]
}

function isValidHostname() {
	[[ $1 =~ ^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$ ]] && [[ $1 == *[A-Za-z]* ]]
}

function isPrivateIpv4() {
	# RFC 1918, RFC 6598 (carrier-grade NAT) and link-local ranges
	[[ $1 =~ ^10\. ]] ||
		[[ $1 =~ ^192\.168\. ]] ||
		[[ $1 =~ ^172\.(1[6-9]|2[0-9]|3[01])\. ]] ||
		[[ $1 =~ ^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\. ]] ||
		[[ $1 =~ ^169\.254\. ]]
}

function isValidIpv6Prefix() {
	[[ $1 =~ ^[0-9a-fA-F:]+/[0-9]{1,3}$ ]] || return 1
	if command -v python3 &>/dev/null; then
		python3 -c 'import ipaddress, sys; ipaddress.ip_network(sys.argv[1], strict=False)' "$1" 2>/dev/null
	fi
}

function suggestPublicIpv6() {
	# suggestPublicIpv6 <prefix> [excluded address...]: first free host address from ::2
	python3 - "$@" 2>/dev/null <<'PYTHON'
import ipaddress
import sys

network = ipaddress.ip_network(sys.argv[1], strict=False)
excluded = {ipaddress.ip_address(address) for address in sys.argv[2:]}
for offset in range(2, min(network.num_addresses, 65536)):
    if network[offset] not in excluded:
        print(network[offset])
        break
PYTHON
}

function buildClientAddressLine() {
	local PRIVATE_IPV4=$1
	local PUBLIC_IPV4=$2
	local PRIVATE_IPV6=$3
	local PUBLIC_IPV6=$4
	local ADDRESSES=""
	local ADDRESS

	for ADDRESS in \
		"${PUBLIC_IPV4:+${PUBLIC_IPV4}/32}" \
		"${PRIVATE_IPV4:+${PRIVATE_IPV4}/32}" \
		"${PUBLIC_IPV6:+${PUBLIC_IPV6}/128}" \
		"${PRIVATE_IPV6:+${PRIVATE_IPV6}/128}"; do
		if [[ -z ${ADDRESS} ]]; then
			continue
		elif [[ -z ${ADDRESSES} ]]; then
			ADDRESSES=${ADDRESS}
		else
			ADDRESSES="${ADDRESSES},${ADDRESS}"
		fi
	done

	echo "${ADDRESSES}"
}

function validateClientAddressMode() {
	local CLIENT_ADDRESS_MODE=$1
	local PRIVATE_IPV4=$2
	local PUBLIC_IPV4=$3
	local PRIVATE_IPV6=$4
	local PUBLIC_IPV6=$5

	case "${CLIENT_ADDRESS_MODE}" in
	private)
		[[ (-n ${PRIVATE_IPV4} || -n ${PRIVATE_IPV6}) && -z ${PUBLIC_IPV4} && -z ${PUBLIC_IPV6} ]]
		;;
	public)
		[[ (-n ${PUBLIC_IPV4} || -n ${PUBLIC_IPV6}) && -z ${PRIVATE_IPV4} && -z ${PRIVATE_IPV6} ]]
		;;
	mixed)
		[[ (-n ${PRIVATE_IPV4} || -n ${PRIVATE_IPV6}) && (-n ${PUBLIC_IPV4} || -n ${PUBLIC_IPV6}) ]]
		;;
	*)
		return 1
		;;
	esac
}

function buildPeerAllowedIps() {
	local PRIVATE_IPV4=$1
	local PUBLIC_IPV4=$2
	local PRIVATE_IPV6=$3
	local PUBLIC_IPV6=$4

	buildClientAddressLine "${PRIVATE_IPV4}" "${PUBLIC_IPV4}" "${PRIVATE_IPV6}" "${PUBLIC_IPV6}"
}

function buildSysctlConfig() {
	local PUBLIC_ROUTING_MODE=$1
	local SERVER_PUB_NIC=$2

	echo "net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
# Forwarding makes the kernel ignore router advertisements unless accept_ra=2
net.ipv6.conf.${SERVER_PUB_NIC}.accept_ra = 2"

	if [[ ${PUBLIC_ROUTING_MODE} == "yes" ]]; then
		# Needed for the per-address NDP proxy entries added by the hooks
		echo "net.ipv6.conf.all.proxy_ndp = 1"
	fi
}

function applySysctlConfig() {
	# systemd-sysctl ships with systemd-udev on Enterprise Linux, which minimal images may lack
	if ! systemctl restart systemd-sysctl.service 2>/dev/null; then
		sysctl -q -p /etc/sysctl.d/wg.conf
	fi
}

function buildNftRuleset() {
	# buildNftRuleset <public nic> <wg nic> <wg ipv4> <wg ipv6> <wg mtu>
	local SERVER_PUB_NIC=$1
	local SERVER_WG_NIC=$2
	local SERVER_WG_IPV4=$3
	local SERVER_WG_IPV6=$4
	local SERVER_WG_MTU=$5
	local PRIVATE_IPV4_CIDR
	local PRIVATE_IPV6_CIDR
	local MSS_IPV4=$((SERVER_WG_MTU - 40))
	local MSS_IPV6=$((SERVER_WG_MTU - 60))

	PRIVATE_IPV4_CIDR=$(echo "${SERVER_WG_IPV4}" | awk -F '.' '{ print $1 "." $2 "." $3 ".0/24" }')
	PRIVATE_IPV6_CIDR="$(echo "${SERVER_WG_IPV6}" | awk -F '::' '{ print $1 }')::/64"

	# Accept rules belong to the host firewall: a separate nftables table cannot
	# override another table's drop policy, so this one only does what it owns.
	echo "# Generated by wireguard-install for ${SERVER_WG_NIC}: NAT for the private tunnel
# subnets and TCP MSS clamping to the tunnel MTU in both directions.
table inet wireguard
delete table inet wireguard
table inet wireguard {
	chain forward {
		type filter hook forward priority mangle; policy accept;
		meta nfproto ipv4 iifname \"${SERVER_WG_NIC}\" tcp flags syn tcp option maxseg size > ${MSS_IPV4} tcp option maxseg size set ${MSS_IPV4}
		meta nfproto ipv4 oifname \"${SERVER_WG_NIC}\" tcp flags syn tcp option maxseg size > ${MSS_IPV4} tcp option maxseg size set ${MSS_IPV4}
		meta nfproto ipv6 iifname \"${SERVER_WG_NIC}\" tcp flags syn tcp option maxseg size > ${MSS_IPV6} tcp option maxseg size set ${MSS_IPV6}
		meta nfproto ipv6 oifname \"${SERVER_WG_NIC}\" tcp flags syn tcp option maxseg size > ${MSS_IPV6} tcp option maxseg size set ${MSS_IPV6}
	}

	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname \"${SERVER_PUB_NIC}\" ip saddr ${PRIVATE_IPV4_CIDR} masquerade
		oifname \"${SERVER_PUB_NIC}\" ip6 saddr ${PRIVATE_IPV6_CIDR} masquerade
	}
}"
}

function buildHookBlock() {
	# buildHookBlock <wg nic> <public nic> <public ipv4 list> <public ipv6 list>
	local SERVER_WG_NIC=$1
	local SERVER_PUB_NIC=$2
	local PUBLIC_IPV4_LIST=$3
	local PUBLIC_IPV6_LIST=$4
	local HOOKS
	local ADDRESS

	HOOKS="PostUp = nft -f /etc/wireguard/${SERVER_WG_NIC}.nft
PostDown = nft delete table inet wireguard || true"

	# Proxy ARP/NDP entries make the server answer for on-link public addresses
	while IFS= read -r ADDRESS; do
		[[ -n ${ADDRESS} ]] || continue
		HOOKS="${HOOKS}
PostUp = ip -4 neigh replace proxy ${ADDRESS} dev ${SERVER_PUB_NIC}
PostDown = ip -4 neigh del proxy ${ADDRESS} dev ${SERVER_PUB_NIC} || true"
	done <<<"${PUBLIC_IPV4_LIST}"

	while IFS= read -r ADDRESS; do
		[[ -n ${ADDRESS} ]] || continue
		HOOKS="${HOOKS}
PostUp = ip -6 neigh replace proxy ${ADDRESS} dev ${SERVER_PUB_NIC}
PostDown = ip -6 neigh del proxy ${ADDRESS} dev ${SERVER_PUB_NIC} || true"
	done <<<"${PUBLIC_IPV6_LIST}"

	echo "${HOOKS}"
}

function buildClientConfig() {
	local WG_INTERFACE_MTU=$1
	local CLIENT_PRIV_KEY=$2
	local SERVER_PUB_KEY=$3
	local CLIENT_PRE_SHARED_KEY=$4
	local ENDPOINT=$5
	local ALLOWED_IPS=$6
	local CLIENT_DNS_1=$7
	local CLIENT_DNS_2=$8
	local PRIVATE_IPV4=$9
	local PUBLIC_IPV4=${10}
	local PRIVATE_IPV6=${11}
	local PUBLIC_IPV6=${12}

	# No hooks: the server clamps the MSS for every flow, so phones and Windows work too
	echo "[Interface]
PrivateKey = ${CLIENT_PRIV_KEY}
Address = $(buildClientAddressLine "${PRIVATE_IPV4}" "${PUBLIC_IPV4}" "${PRIVATE_IPV6}" "${PUBLIC_IPV6}")
DNS = ${CLIENT_DNS_1},${CLIENT_DNS_2}
MTU = ${WG_INTERFACE_MTU}

[Peer]
PublicKey = ${SERVER_PUB_KEY}
PresharedKey = ${CLIENT_PRE_SHARED_KEY}
Endpoint = ${ENDPOINT}
AllowedIPs = ${ALLOWED_IPS}
PersistentKeepalive = 15"
}

function buildServerPeerBlock() {
	local CLIENT_NAME=$1
	local CLIENT_ADDRESS_MODE=$2
	local CLIENT_PUB_KEY=$3
	local CLIENT_PRE_SHARED_KEY=$4
	local PRIVATE_IPV4=$5
	local PUBLIC_IPV4=$6
	local PRIVATE_IPV6=$7
	local PUBLIC_IPV6=$8
	local ENDPOINT=$9

	echo "### Client ${CLIENT_NAME}
# AddressMode: ${CLIENT_ADDRESS_MODE}
# PrivateIPv4: ${PRIVATE_IPV4}
# PublicIPv4: ${PUBLIC_IPV4}
# PrivateIPv6: ${PRIVATE_IPV6}
# PublicIPv6: ${PUBLIC_IPV6}
# Endpoint: ${ENDPOINT}
[Peer]
PublicKey = ${CLIENT_PUB_KEY}
PresharedKey = ${CLIENT_PRE_SHARED_KEY}
AllowedIPs = $(buildPeerAllowedIps "${PRIVATE_IPV4}" "${PUBLIC_IPV4}" "${PRIVATE_IPV6}" "${PUBLIC_IPV6}")
PersistentKeepalive = 15"
}

function formatEndpoint() {
	# formatEndpoint <host> <port>: IPv6 literals need brackets
	if isValidIpv6 "$1"; then
		echo "[$1]:$2"
	else
		echo "$1:$2"
	fi
}

function listPublicAddresses() {
	# listPublicAddresses <PublicIPv4|PublicIPv6> <peer blocks>
	echo "$2" | awk -F ': ' -v KEY="# $1: " 'index($0, KEY) == 1 && $2 != "" { print $2 }'
}

function getPeerBlocksFromConfig() {
	local WG_CONF_FILE=$1

	if [[ -e ${WG_CONF_FILE} ]]; then
		awk 'BEGIN { printing = 0 } /^### Client / { printing = 1 } printing { print }' "${WG_CONF_FILE}"
	fi
}

function writeServerConfig() {
	# writeServerConfig <config file> <peer blocks>
	local WG_CONF_FILE=$1
	local PEER_BLOCKS=$2

	printf '%s\n' "$(buildNftRuleset "${SERVER_PUB_NIC}" "${SERVER_WG_NIC}" "${SERVER_WG_IPV4}" "${SERVER_WG_IPV6}" "${SERVER_WG_MTU}")" >"/etc/wireguard/${SERVER_WG_NIC}.nft"
	chmod 600 "/etc/wireguard/${SERVER_WG_NIC}.nft"

	printf '[Interface]\nAddress = %s/24,%s/64\nListenPort = %s\nMTU = %s\nPrivateKey = %s\n' \
		"${SERVER_WG_IPV4}" \
		"${SERVER_WG_IPV6}" \
		"${SERVER_PORT}" \
		"${SERVER_WG_MTU}" \
		"${SERVER_PRIV_KEY}" >"${WG_CONF_FILE}"
	printf '%s\n' "$(buildHookBlock \
		"${SERVER_WG_NIC}" \
		"${SERVER_PUB_NIC}" \
		"$(listPublicAddresses PublicIPv4 "${PEER_BLOCKS}")" \
		"$(listPublicAddresses PublicIPv6 "${PEER_BLOCKS}")")" >>"${WG_CONF_FILE}"

	if [[ -n ${PEER_BLOCKS} ]]; then
		printf '\n%s\n' "${PEER_BLOCKS}" >>"${WG_CONF_FILE}"
	fi

	chmod 600 "${WG_CONF_FILE}"
}

function listProxyEntries() {
	# listProxyEntries <config file>: "<-4|-6> <address> dev <nic>" per proxy hook
	getHooksFromConfig "$1" | sed -n 's/^PostUp = ip \(-[46]\) neigh replace proxy \(.*\)$/\1 \2/p'
}

function getHooksFromConfig() {
	local WG_CONF_FILE=$1

	if [[ -e ${WG_CONF_FILE} ]]; then
		grep -E '^Post(Up|Down) = ' "${WG_CONF_FILE}"
	fi
}

function buildAnnouncementScript() {
	cat <<'SCRIPT'
#!/usr/bin/env python3
"""Announce public IPv4 addresses routed through WireGuard with gratuitous ARP.

Generated by wireguard-install: rewritten whenever clients change.

The upstream router must learn that these addresses live behind this host's
MAC address, and some providers only refresh their ARP caches from gratuitous
ARP. Every ANNOUNCE_INTERVAL seconds each address gets a gratuitous request
(RFC 5227) and a gratuitous reply. arping cannot do this for an address the
host does not own, hence the raw socket.
"""
import os
import socket
import struct
import sys
import time

BROADCAST = b"\xff" * 6
ETH_P_ARP = 0x0806


def arp_frame(operation, mac, ip):
    """Broadcast Ethernet frame carrying a gratuitous ARP request (1) or reply (2)."""
    target_mac = b"\x00" * 6 if operation == 1 else BROADCAST
    arp = struct.pack("!HHBBH6s4s6s4s", 1, 0x0800, 6, 4, operation, mac, ip, target_mac, ip)
    return BROADCAST + mac + struct.pack("!H", ETH_P_ARP) + arp


def main():
    nic = os.environ["SERVER_PUB_NIC"]
    addresses = os.environ["PUBLIC_IPV4_LIST"].split()
    interval = float(os.environ.get("ANNOUNCE_INTERVAL", "1"))

    with open(f"/sys/class/net/{nic}/address") as address_file:
        mac = bytes.fromhex(address_file.read().strip().replace(":", ""))
    sock = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(ETH_P_ARP))
    sock.bind((nic, 0))
    frames = [arp_frame(op, mac, socket.inet_aton(a)) for a in addresses for op in (1, 2)]

    print(f"Announcing {' '.join(addresses)} on {nic} every {interval:g}s", flush=True)
    while True:
        for frame in frames:
            sock.send(frame)
        time.sleep(interval)


if __name__ == "__main__":
    try:
        main()
    except OSError as error:
        # Usually a missing or renamed interface: exit and let systemd retry
        print(f"Cannot announce on {os.environ.get('SERVER_PUB_NIC', '?')}: {error}", file=sys.stderr)
        sys.exit(1)
SCRIPT
}

function buildAnnouncementEnvironment() {
	local SERVER_PUB_NIC=$1
	local PUBLIC_IPV4_LIST=$2

	echo "# Generated by wireguard-install: rewritten whenever clients change.
SERVER_PUB_NIC=${SERVER_PUB_NIC}
PUBLIC_IPV4_LIST=\"${PUBLIC_IPV4_LIST}\"
ANNOUNCE_INTERVAL=1"
}

function buildAnnouncementSystemdUnit() {
	local PYTHON3=$1

	echo "[Unit]
Description=Announce public IPv4 addresses routed through WireGuard interface %i
Documentation=https://github.com/tbringuier/wireguard-install
BindsTo=wg-quick@%i.service
After=wg-quick@%i.service network-online.target
Wants=network-online.target
# Restarted on every client change, so the default start rate limit does not apply
StartLimitIntervalSec=0

[Service]
Type=simple
EnvironmentFile=/etc/wireguard/public-ipv4-announce-%i.env
ExecStart=${PYTHON3} /etc/wireguard/wg-public-ipv4-announce.py
Restart=always
RestartSec=5

# Sending raw ARP frames is all this service does
CapabilityBoundingSet=CAP_NET_RAW
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ProtectKernelTunables=true
ProtectControlGroups=true

[Install]
WantedBy=wg-quick@%i.service"
}

function removeLegacyPublicIpv4AnnouncementService() {
	# Versions of this fork before October 2026 installed a non-template unit
	if [[ -e /etc/systemd/system/wg-public-ipv4-arping.service ]]; then
		systemctl disable --now wg-public-ipv4-arping.service >/dev/null 2>&1 || true
		rm -f /etc/systemd/system/wg-public-ipv4-arping.service
		rm -f /etc/wireguard/wg-public-ipv4-arping.sh /etc/wireguard/public-ipv4.list
		systemctl daemon-reload
	fi
}

function refreshPublicIpv4AnnouncementService() {
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"
	local UNIT="wg-public-ipv4-announce@${SERVER_WG_NIC}.service"
	local ENV_FILE="/etc/wireguard/public-ipv4-announce-${SERVER_WG_NIC}.env"
	local PUBLIC_IPV4_LIST
	local PYTHON3

	if [[ ${PUBLIC_ROUTING_MODE} != 'yes' ]]; then
		return
	fi

	removeLegacyPublicIpv4AnnouncementService

	PUBLIC_IPV4_LIST=$(listPublicAddresses PublicIPv4 "$(getPeerBlocksFromConfig "${WG_CONF_FILE}")" | paste -sd ' ')

	if [[ -z ${PUBLIC_IPV4_LIST} ]]; then
		# Nothing to announce: keep the unit file around but inactive
		systemctl disable --now "${UNIT}" >/dev/null 2>&1 || true
		rm -f "${ENV_FILE}"
		return
	fi

	if ! PYTHON3=$(command -v python3); then
		echo -e "${ORANGE}python3 is not available: public IPv4 addresses are not announced with gratuitous ARP.${NC}"
		echo -e "${ORANGE}The server still answers ARP requests for them (proxy ARP), which is enough with most providers.${NC}"
		return
	fi

	printf '%s\n' "$(buildAnnouncementScript)" >/etc/wireguard/wg-public-ipv4-announce.py
	chmod 600 /etc/wireguard/wg-public-ipv4-announce.py
	printf '%s\n' "$(buildAnnouncementEnvironment "${SERVER_PUB_NIC}" "${PUBLIC_IPV4_LIST}")" >"${ENV_FILE}"
	chmod 600 "${ENV_FILE}"
	printf '%s\n' "$(buildAnnouncementSystemdUnit "${PYTHON3}")" >/etc/systemd/system/wg-public-ipv4-announce@.service

	# The unit is wanted by wg-quick@<interface>, so it follows the tunnel across reboots
	systemctl daemon-reload
	systemctl enable "${UNIT}" >/dev/null 2>&1
	if ! systemctl restart "${UNIT}"; then
		echo -e "${ORANGE}The public IPv4 announcement service could not be started, check: journalctl -u ${UNIT}${NC}"
	fi
}

function removePublicIpv4AnnouncementService() {
	removeLegacyPublicIpv4AnnouncementService

	systemctl disable --now "wg-public-ipv4-announce@${SERVER_WG_NIC}.service" >/dev/null 2>&1 || true
	rm -f /etc/systemd/system/wg-public-ipv4-announce@.service
	rm -f /etc/wireguard/wg-public-ipv4-announce.py "/etc/wireguard/public-ipv4-announce-${SERVER_WG_NIC}.env"
	systemctl daemon-reload
}

function applyServerConfig() {
	# applyServerConfig <peer blocks>
	# Regenerates the server configuration and applies it live: peers through
	# wg syncconf, proxy ARP/NDP entries through ip neigh. Only a change in the
	# other hooks (a migration, an edited parameter) stops and starts the tunnel,
	# since wg-quick runs PostDown from the file on disk.
	local PEER_BLOCKS=$1
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"
	local NEW_CONF_FILE="${WG_CONF_FILE}.new"
	local UNIT="wg-quick@${SERVER_WG_NIC}.service"
	local TUNNEL_ACTIVE=no
	local PROXIES_BEFORE
	local PROXIES_AFTER
	local ENTRY

	writeServerConfig "${NEW_CONF_FILE}" "${PEER_BLOCKS}"

	if systemctl is-active --quiet "${UNIT}"; then
		TUNNEL_ACTIVE=yes
	fi

	if [[ ${TUNNEL_ACTIVE} == yes && $(getHooksFromConfig "${WG_CONF_FILE}" | grep -v ' neigh ') != "$(getHooksFromConfig "${NEW_CONF_FILE}" | grep -v ' neigh ')" ]]; then
		systemctl stop "${UNIT}"
		TUNNEL_ACTIVE=no
	fi

	PROXIES_BEFORE=$(listProxyEntries "${WG_CONF_FILE}" | sort)
	PROXIES_AFTER=$(listProxyEntries "${NEW_CONF_FILE}" | sort)
	cp -p "${WG_CONF_FILE}" "${WG_CONF_FILE}.bak"
	mv "${NEW_CONF_FILE}" "${WG_CONF_FILE}"

	if [[ ${TUNNEL_ACTIVE} == yes ]]; then
		wg syncconf "${SERVER_WG_NIC}" <(wg-quick strip "${SERVER_WG_NIC}")
		while read -r ENTRY; do
			# shellcheck disable=SC2086
			[[ -n ${ENTRY} ]] && ip ${ENTRY%% *} neigh del proxy ${ENTRY#* } 2>/dev/null
		done <<<"$(comm -23 <(echo "${PROXIES_BEFORE}") <(echo "${PROXIES_AFTER}"))"
		while read -r ENTRY; do
			# shellcheck disable=SC2086
			[[ -n ${ENTRY} ]] && ip ${ENTRY%% *} neigh replace proxy ${ENTRY#* }
		done <<<"$(comm -13 <(echo "${PROXIES_BEFORE}") <(echo "${PROXIES_AFTER}"))"
	else
		systemctl start "${UNIT}"
	fi

	refreshPublicIpv4AnnouncementService
}

function installPackages() {
	if ! "$@"; then
		echo -e "${RED}Failed to install packages.${NC}"
		echo "Please check your internet connection and package sources."
		exit 1
	fi
}

function installOptionalPackages() {
	if ! "$@"; then
		echo -e "${ORANGE}Optional packages could not be installed, continuing without them.${NC}"
	fi
}

function hasWireGuardKernelSupport() {
	# Creating an interface is the only reliable test: the module may be built in,
	# autoloaded, or missing on a kernel older than 5.6.
	modprobe wireguard >/dev/null 2>&1 || true
	if ip link add wg-probe type wireguard >/dev/null 2>&1; then
		ip link del wg-probe
		return 0
	fi
	return 1
}

function isRoot() {
	if [ "${EUID}" -ne 0 ]; then
		echo "You need to run this script as root"
		exit 1
	fi
}

function checkSystemd() {
	if [[ ! -d /run/systemd/system ]] || ! command -v systemctl &>/dev/null; then
		echo "This script requires systemd as the init system."
		exit 1
	fi
}

function waitForCloudInit() {
	# A fresh cloud instance may still be configured by cloud-init
	if command -v cloud-init &>/dev/null && [[ -d /run/cloud-init ]]; then
		if ! cloud-init status >/dev/null 2>&1; then
			return
		fi
		if [[ $(cloud-init status 2>/dev/null) == *running* ]]; then
			echo "Waiting for cloud-init to finish..."
			cloud-init status --wait >/dev/null 2>&1 || true
		fi
	fi
}

function checkVirt() {
	VIRT=$(systemd-detect-virt)
	if [[ ${VIRT} == "openvz" ]]; then
		echo "OpenVZ is not supported"
		exit 1
	fi
	if [[ ${VIRT} == "lxc" ]]; then
		echo "LXC is not supported (yet)."
		echo "WireGuard can technically run in an LXC container,"
		echo "but the kernel module has to be installed on the host,"
		echo "the container has to be run with some specific parameters"
		echo "and only the tools need to be installed in the container."
		exit 1
	fi
}

function checkOS() {
	if [[ ! -e /etc/os-release ]]; then
		echo "Unable to detect the distribution: /etc/os-release is missing."
		exit 1
	fi
	source /etc/os-release
	OS="${ID}"
	OS_FAMILY=""

	# Map the distribution (or the ones it derives from) to a package family
	local CANDIDATE
	for CANDIDATE in ${ID} ${ID_LIKE:-}; do
		case "${CANDIDATE}" in
		debian | ubuntu | raspbian)
			OS_FAMILY=debian
			;;
		fedora | rhel | centos | almalinux | rocky | ol)
			OS_FAMILY=rhel
			;;
		arch | archarm | manjaro)
			OS_FAMILY=arch
			;;
		suse | opensuse | opensuse-leap | opensuse-tumbleweed | sles)
			OS_FAMILY=suse
			;;
		flatcar)
			OS_FAMILY=flatcar
			;;
		*)
			continue
			;;
		esac
		break
	done

	# Unknown distribution: fall back on the package manager that is available
	if [[ -z ${OS_FAMILY} ]]; then
		if command -v apt-get &>/dev/null; then
			OS_FAMILY=debian
		elif command -v dnf &>/dev/null; then
			OS_FAMILY=rhel
		elif command -v pacman &>/dev/null; then
			OS_FAMILY=arch
		elif command -v zypper &>/dev/null; then
			OS_FAMILY=suse
		else
			echo "Looks like you aren't running this installer on a supported system (${PRETTY_NAME:-${ID}})."
			echo "Supported package managers: apt-get, dnf, pacman, zypper. Flatcar Linux is supported as-is."
			exit 1
		fi
	fi

	# Reject releases whose kernel or repositories predate WireGuard
	local MAJOR_VERSION="${VERSION_ID%%.*}"
	if [[ -n ${MAJOR_VERSION} && ${MAJOR_VERSION} =~ ^[0-9]+$ ]]; then
		case "${OS}" in
		debian | raspbian)
			if [[ ${MAJOR_VERSION} -lt 11 ]]; then
				echo "Your version of Debian (${VERSION_ID}) is not supported. Please use Debian 11 Bullseye or later"
				exit 1
			fi
			;;
		ubuntu)
			if [[ ${MAJOR_VERSION} -lt 20 ]]; then
				echo "Your version of Ubuntu (${VERSION_ID}) is not supported. Please use Ubuntu 20.04 or later"
				exit 1
			fi
			;;
		fedora)
			if [[ ${MAJOR_VERSION} -lt 32 ]]; then
				echo "Your version of Fedora (${VERSION_ID}) is not supported. Please use Fedora 32 or later"
				exit 1
			fi
			;;
		centos | almalinux | rocky | rhel | ol)
			if [[ ${MAJOR_VERSION} -lt 8 ]]; then
				echo "Your version of ${PRETTY_NAME:-${ID}} is not supported. Please use release 8 or later"
				exit 1
			fi
			;;
		esac
	fi
}

function getHomeDirForClient() {
	local CLIENT_NAME=$1

	if [[ -z ${CLIENT_NAME} ]]; then
		echo "Error: getHomeDirForClient() requires a client name as argument"
		exit 1
	fi

	# Prefer the home of a user named like the client, then the sudo caller's, then root's
	if [[ -e "/home/${CLIENT_NAME}" ]]; then
		echo "/home/${CLIENT_NAME}"
	elif [[ -n ${SUDO_USER:-} && ${SUDO_USER} != root ]]; then
		echo "/home/${SUDO_USER}"
	else
		echo "/root"
	fi
}

function initialCheck() {
	isRoot
	checkSystemd
	checkOS
	checkVirt
	waitForCloudInit
}

function fetchPublicIpv4() {
	local URL
	local ADDRESS

	for URL in https://api.ipify.org https://ifconfig.me/ip https://icanhazip.com; do
		if command -v curl &>/dev/null; then
			ADDRESS=$(curl -4 -fsS --max-time 5 "${URL}" 2>/dev/null)
		elif command -v wget &>/dev/null; then
			ADDRESS=$(wget -4 -qO- --timeout=5 "${URL}" 2>/dev/null)
		else
			return 1
		fi
		ADDRESS=$(echo "${ADDRESS}" | tr -d '[:space:]')
		if isValidIpv4 "${ADDRESS}"; then
			echo "${ADDRESS}"
			return 0
		fi
	done

	return 1
}

function detectPublicIpv4() {
	local ADDRESS
	local EXTERNAL_ADDRESS

	ADDRESS=$(ip -4 -o addr show scope global 2>/dev/null | awk '{ print $4 }' | cut -d '/' -f 1 | head -1)
	if [[ -n ${ADDRESS} ]] && isPrivateIpv4 "${ADDRESS}"; then
		# Cloud instances behind 1:1 NAT only carry a private address
		EXTERNAL_ADDRESS=$(fetchPublicIpv4) && ADDRESS=${EXTERNAL_ADDRESS}
	fi

	echo "${ADDRESS}"
}

function detectPublicIpv6() {
	# First global address that is not a ULA (fc00::/7)
	ip -6 -o addr show scope global 2>/dev/null | awk '{ print $4 }' | cut -d '/' -f 1 | grep -v -i -E '^f[cd]' | head -1
}

function detectPublicIpv6Prefix() {
	# detectPublicIpv6Prefix <nic>: first global, non-ULA network of /64 or shorter
	ip -6 -o addr show dev "$1" scope global 2>/dev/null | awk '{ print $4 }' | grep -v -i -E '^f[cd]' | python3 -c '
import ipaddress
import sys

for line in sys.stdin:
    network = ipaddress.ip_interface(line.strip()).network
    if network.prefixlen <= 64:
        print(network)
        break
' 2>/dev/null
}

function listServerIpv6Addresses() {
	ip -6 -o addr show dev "${SERVER_PUB_NIC}" scope global 2>/dev/null | awk '{ print $4 }' | cut -d '/' -f 1
}

function readOptionalValue() {
	# readOptionalValue <variable> <prompt> <default> <validator>: empty is accepted
	local VARIABLE=$1
	local PROMPT=$2
	local DEFAULT=$3
	local VALIDATOR=$4
	local VALUE

	while :; do
		read -rp "${PROMPT}: " -e -i "${DEFAULT}" VALUE
		if [[ -z ${VALUE} ]] || "${VALIDATOR}" "${VALUE}"; then
			break
		fi
		echo -e "${ORANGE}${VALUE} is not valid.${NC}"
	done

	printf -v "${VARIABLE}" '%s' "${VALUE}"
}

function detectPublicNic() {
	local NIC

	NIC=$(ip -4 -o route show default 2>/dev/null | awk '{ for (i = 1; i <= NF; i++) if ($i == "dev") print $(i + 1) }' | head -1)
	if [[ -z ${NIC} ]]; then
		NIC=$(ip -6 -o route show default 2>/dev/null | awk '{ for (i = 1; i <= NF; i++) if ($i == "dev") print $(i + 1) }' | head -1)
	fi

	echo "${NIC}"
}

function detectHostFirewall() {
	if systemctl is-active --quiet firewalld; then
		echo firewalld
	elif command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q '^Status: active'; then
		echo ufw
	else
		echo none
	fi
}

function firewalldPublicZone() {
	firewall-cmd --get-zone-of-interface="${SERVER_PUB_NIC}" 2>/dev/null || firewall-cmd --get-default-zone
}

function applyFirewallIntegration() {
	# Open the listening port and allow forwarding on the tunnel in the host firewall
	local PUBLIC_ZONE

	case "${FIREWALL_INTEGRATION}" in
	ufw)
		ufw allow "${SERVER_PORT}/udp" >/dev/null
		ufw route allow in on "${SERVER_WG_NIC}" >/dev/null
		ufw route allow out on "${SERVER_WG_NIC}" >/dev/null
		;;
	firewalld)
		PUBLIC_ZONE=$(firewalldPublicZone)
		firewall-cmd --permanent --zone="${PUBLIC_ZONE}" --add-port="${SERVER_PORT}/udp" >/dev/null
		firewall-cmd --permanent --zone=trusted --add-interface="${SERVER_WG_NIC}" >/dev/null
		firewall-cmd --permanent --new-policy=wg-forward-out >/dev/null 2>&1 || true
		firewall-cmd --permanent --policy=wg-forward-out --add-ingress-zone=trusted >/dev/null
		firewall-cmd --permanent --policy=wg-forward-out --add-egress-zone="${PUBLIC_ZONE}" >/dev/null
		firewall-cmd --permanent --policy=wg-forward-out --set-target=ACCEPT >/dev/null
		firewall-cmd --permanent --new-policy=wg-forward-in >/dev/null 2>&1 || true
		firewall-cmd --permanent --policy=wg-forward-in --add-ingress-zone="${PUBLIC_ZONE}" >/dev/null
		firewall-cmd --permanent --policy=wg-forward-in --add-egress-zone=trusted >/dev/null
		firewall-cmd --permanent --policy=wg-forward-in --set-target=ACCEPT >/dev/null
		firewall-cmd --reload >/dev/null
		;;
	esac
}

function removeFirewallIntegration() {
	local PUBLIC_ZONE

	case "${FIREWALL_INTEGRATION}" in
	ufw)
		ufw --force delete allow "${SERVER_PORT}/udp" >/dev/null 2>&1
		ufw --force route delete allow in on "${SERVER_WG_NIC}" >/dev/null 2>&1
		ufw --force route delete allow out on "${SERVER_WG_NIC}" >/dev/null 2>&1
		;;
	firewalld)
		PUBLIC_ZONE=$(firewalldPublicZone)
		firewall-cmd --permanent --zone="${PUBLIC_ZONE}" --remove-port="${SERVER_PORT}/udp" >/dev/null 2>&1
		firewall-cmd --permanent --zone=trusted --remove-interface="${SERVER_WG_NIC}" >/dev/null 2>&1
		firewall-cmd --permanent --delete-policy=wg-forward-out >/dev/null 2>&1
		firewall-cmd --permanent --delete-policy=wg-forward-in >/dev/null 2>&1
		firewall-cmd --reload >/dev/null 2>&1
		;;
	esac
}

function warnAboutOtherFirewalls() {
	# Filters the installer does not manage but that drop forwarded traffic
	if systemctl is-active --quiet docker; then
		echo -e "${ORANGE}Docker is running and its FORWARD policy drops unknown traffic. If clients have no connectivity, run:${NC}"
		echo "  iptables -I DOCKER-USER -i ${SERVER_WG_NIC} -j ACCEPT; iptables -I DOCKER-USER -o ${SERVER_WG_NIC} -j ACCEPT"
	fi
	if [[ $(detectHostFirewall) == none ]] && nft list ruleset 2>/dev/null | grep -qE 'hook (input|forward).*policy drop'; then
		echo -e "${ORANGE}An nftables ruleset with a drop policy is loaded: it must accept UDP port ${SERVER_PORT} and forwarding on ${SERVER_WG_NIC}.${NC}"
	fi
}

function installQuestions() {
	echo "Welcome to the WireGuard installer!"
	echo "The git repository is available at: https://github.com/tbringuier/wireguard-install"
	echo ""
	echo "I need to ask you a few questions before starting the setup."
	echo "You can keep the default options and just press enter if you are ok with them."
	echo ""

	# Clients can use any of the server's public addresses as endpoint, so ask for all of them
	echo "Public addresses of this server (leave empty the ones it does not have):"
	until [[ -n ${SERVER_PUB_IPV4}${SERVER_PUB_IPV6}${SERVER_HOSTNAME} ]]; do
		readOptionalValue SERVER_PUB_IPV4 "Public IPv4" "$(detectPublicIpv4)" isValidIpv4
		readOptionalValue SERVER_PUB_IPV6 "Public IPv6" "$(detectPublicIpv6)" isValidIpv6
		readOptionalValue SERVER_HOSTNAME "Hostname pointing to this server" "" isValidHostname
		if [[ -z ${SERVER_PUB_IPV4}${SERVER_PUB_IPV6}${SERVER_HOSTNAME} ]]; then
			echo -e "${ORANGE}At least one public address or hostname is needed.${NC}"
		fi
	done

	# Detect public interface and pre-fill for the user
	SERVER_NIC=$(detectPublicNic)
	until [[ ${SERVER_PUB_NIC} =~ ^[a-zA-Z0-9_]+$ ]]; do
		read -rp "Public interface: " -e -i "${SERVER_NIC}" SERVER_PUB_NIC
	done

	until [[ ${SERVER_WG_NIC} =~ ^[a-zA-Z0-9_]+$ && ${#SERVER_WG_NIC} -lt 16 ]]; do
		read -rp "WireGuard interface name: " -e -i wg0 SERVER_WG_NIC
	done

	# Tunnel MTU: the public link minus the WireGuard overhead, capped at the usual 1420
	DEFAULT_WG_MTU=$(($(cat "/sys/class/net/${SERVER_PUB_NIC}/mtu" 2>/dev/null || echo 1500) - 80))
	if [[ ${DEFAULT_WG_MTU} -gt 1420 ]]; then
		DEFAULT_WG_MTU=1420
	elif [[ ${DEFAULT_WG_MTU} -lt 1280 ]]; then
		DEFAULT_WG_MTU=1280
	fi
	until [[ ${SERVER_WG_MTU} =~ ^[0-9]+$ ]] && [[ ${SERVER_WG_MTU} -ge 1280 && ${SERVER_WG_MTU} -le 1500 ]]; do
		read -rp "Tunnel MTU [1280-1500]: " -e -i "${DEFAULT_WG_MTU}" SERVER_WG_MTU
	done

	until isValidIpv4 "${SERVER_WG_IPV4}"; do
		read -rp "Server WireGuard IPv4: " -e -i 10.66.66.1 SERVER_WG_IPV4
	done

	until [[ ${SERVER_WG_IPV6} =~ ^([a-f0-9]{1,4}:){3,4}: ]]; do
		read -rp "Server WireGuard IPv6: " -e -i fd42:42:42::1 SERVER_WG_IPV6
	done

	# Generate random number within private ports range
	RANDOM_PORT=$(shuf -i49152-65535 -n1)
	until [[ ${SERVER_PORT} =~ ^[0-9]+$ ]] && [ "${SERVER_PORT}" -ge 1 ] && [ "${SERVER_PORT}" -le 65535 ]; do
		read -rp "Server WireGuard port [1-65535]: " -e -i "${RANDOM_PORT}" SERVER_PORT
	done

	# Cloudflare DNS by default
	until isValidIpv4 "${CLIENT_DNS_1}" || isValidIpv6 "${CLIENT_DNS_1}"; do
		read -rp "First DNS resolver to use for the clients: " -e -i 1.1.1.1 CLIENT_DNS_1
	done
	until isValidIpv4 "${CLIENT_DNS_2}" || isValidIpv6 "${CLIENT_DNS_2}"; do
		read -rp "Second DNS resolver to use for the clients (optional): " -e -i 1.0.0.1 CLIENT_DNS_2
		if [[ ${CLIENT_DNS_2} == "" ]]; then
			CLIENT_DNS_2="${CLIENT_DNS_1}"
		fi
	done

	until [[ ${PUBLIC_ROUTING_MODE} =~ ^(yes|no)$ ]]; do
		read -rp "Enable public IP routing support [yes/no]: " -e -i no PUBLIC_ROUTING_MODE
	done

	SERVER_PUB_IPV6_PREFIX=""
	if [[ ${PUBLIC_ROUTING_MODE} == yes ]]; then
		echo "Public clients can get an IPv6 from the block your provider routes to this server."
		readOptionalValue SERVER_PUB_IPV6_PREFIX "Public IPv6 prefix of this server (empty if none)" "$(detectPublicIpv6Prefix "${SERVER_PUB_NIC}")" isValidIpv6Prefix
	fi

	HOST_FIREWALL=$(detectHostFirewall)
	FIREWALL_INTEGRATION=none
	if [[ ${HOST_FIREWALL} != none ]]; then
		echo ""
		echo "${HOST_FIREWALL} is active and drops forwarded traffic by default. WireGuard needs UDP port ${SERVER_PORT}"
		echo "open and forwarding allowed on ${SERVER_WG_NIC}; the installer can add these rules and remove them on uninstall."
		until [[ ${ADD_FIREWALL_RULES} =~ ^(y|n)$ ]]; do
			read -rp "Add the WireGuard rules to ${HOST_FIREWALL}? [y/n]: " -e -i y ADD_FIREWALL_RULES
		done
		if [[ ${ADD_FIREWALL_RULES} == y ]]; then
			FIREWALL_INTEGRATION=${HOST_FIREWALL}
		fi
	fi

	until [[ ${ALLOWED_IPS} =~ ^.+$ ]]; do
		echo -e "\nWireGuard uses a parameter called AllowedIPs to determine what is routed over the VPN."
		read -rp "Allowed IPs list for generated clients (leave default to route everything): " -e -i '0.0.0.0/0,::/0' ALLOWED_IPS
		if [[ ${ALLOWED_IPS} == "" ]]; then
			ALLOWED_IPS="0.0.0.0/0,::/0"
		fi
	done

	echo ""
	echo "Okay, that was all I needed. We are ready to setup your WireGuard server now."
	echo "You will be able to generate a client at the end of the installation."
	read -n1 -r -p "Press any key to continue..."
}

function installWireGuard() {
	# Run setup questions first
	installQuestions

	# Install WireGuard tools and module
	case "${OS_FAMILY}" in
	debian)
		export DEBIAN_FRONTEND=noninteractive
		# cloud-init or unattended-upgrades may still hold the dpkg lock after boot
		local APT_GET=(apt-get -o DPkg::Lock::Timeout=300)
		"${APT_GET[@]}" update
		installPackages "${APT_GET[@]}" install -y wireguard-tools nftables python3
		if ! hasWireGuardKernelSupport; then
			# Kernel older than 5.6: the metapackage pulls the DKMS module
			installOptionalPackages "${APT_GET[@]}" install -y wireguard
		fi
		installOptionalPackages "${APT_GET[@]}" install -y qrencode
		;;
	rhel)
		if [[ ${OS} == 'ol' && ${VERSION_ID%%.*} == 8 ]]; then
			# Oracle Linux 8 ships wireguard-tools in the UEK R6 developer repository
			installPackages dnf install -y oraclelinux-developer-release-el8
			dnf config-manager --disable -y ol8_developer
			dnf config-manager --enable -y ol8_developer_UEKR6
			dnf config-manager --save -y --setopt=ol8_developer_UEKR6.includepkgs='wireguard-tools*'
		elif [[ ${OS} != 'fedora' && ${VERSION_ID%%.*} == 8 ]]; then
			# The EL8 kernel predates WireGuard: use the ELRepo kernel module
			installOptionalPackages dnf install -y epel-release elrepo-release
			installPackages dnf install -y kmod-wireguard
		elif [[ ${OS} != 'fedora' ]]; then
			# qrencode lives in EPEL on Enterprise Linux
			installOptionalPackages dnf install -y epel-release
		fi
		installPackages dnf install -y wireguard-tools nftables python3
		installOptionalPackages dnf install -y qrencode
		;;
	arch)
		installPackages pacman -S --needed --noconfirm wireguard-tools nftables python
		installOptionalPackages pacman -S --needed --noconfirm qrencode
		;;
	suse)
		installPackages zypper --non-interactive install wireguard-tools nftables python3
		installOptionalPackages zypper --non-interactive install qrencode
		;;
	flatcar)
		# Flatcar ships WireGuard and nftables in its read-only /usr
		;;
	esac

	# Verify WireGuard installation
	if ! command -v wg &>/dev/null; then
		echo -e "${RED}WireGuard installation failed. The 'wg' command was not found.${NC}"
		echo "Please check the installation output above for errors."
		exit 1
	fi
	if ! hasWireGuardKernelSupport; then
		echo -e "${ORANGE}The running kernel has no WireGuard support. If the kernel was just updated, reboot and run this script again.${NC}"
	fi
	if ! command -v nft &>/dev/null; then
		echo -e "${RED}The nft command is required (nftables package).${NC}"
		exit 1
	fi
	if ! command -v python3 &>/dev/null; then
		echo -e "${ORANGE}python3 is missing: public IPv4 announcements and IPv6 suggestions are unavailable.${NC}"
	fi

	# Make sure the directory exists with restrictive permissions
	install -d -m 700 /etc/wireguard

	SERVER_PRIV_KEY=$(wg genkey)
	SERVER_PUB_KEY=$(echo "${SERVER_PRIV_KEY}" | wg pubkey)

	# Save WireGuard settings
	echo "SERVER_PUB_IPV4=${SERVER_PUB_IPV4}
SERVER_PUB_IPV6=${SERVER_PUB_IPV6}
SERVER_HOSTNAME=${SERVER_HOSTNAME}
SERVER_PUB_NIC=${SERVER_PUB_NIC}
SERVER_WG_NIC=${SERVER_WG_NIC}
SERVER_WG_IPV4=${SERVER_WG_IPV4}
SERVER_WG_IPV6=${SERVER_WG_IPV6}
SERVER_PORT=${SERVER_PORT}
SERVER_PRIV_KEY=${SERVER_PRIV_KEY}
SERVER_PUB_KEY=${SERVER_PUB_KEY}
CLIENT_DNS_1=${CLIENT_DNS_1}
CLIENT_DNS_2=${CLIENT_DNS_2}
ALLOWED_IPS=${ALLOWED_IPS}
PUBLIC_ROUTING_MODE=${PUBLIC_ROUTING_MODE}
SERVER_PUB_IPV6_PREFIX=${SERVER_PUB_IPV6_PREFIX}
SERVER_WG_MTU=${SERVER_WG_MTU}
FIREWALL_INTEGRATION=${FIREWALL_INTEGRATION}" >/etc/wireguard/params
	chmod 600 /etc/wireguard/params

	# Add server interface
	writeServerConfig "/etc/wireguard/${SERVER_WG_NIC}.conf" ""

	# Enable routing on the server
	install -d /etc/sysctl.d
	printf '%s\n' "$(buildSysctlConfig "${PUBLIC_ROUTING_MODE}" "${SERVER_PUB_NIC}")" >/etc/sysctl.d/wg.conf
	applySysctlConfig

	systemctl enable --now "wg-quick@${SERVER_WG_NIC}"
	applyFirewallIntegration

	refreshPublicIpv4AnnouncementService

	newClient
	echo -e "${GREEN}If you want to add more clients, you simply need to run this script another time!${NC}"

	# Check if WireGuard is running
	systemctl is-active --quiet "wg-quick@${SERVER_WG_NIC}"
	WG_RUNNING=$?

	# WireGuard might not work if we updated the kernel. Tell the user to reboot
	if [[ ${WG_RUNNING} -ne 0 ]]; then
		echo -e "\n${RED}WARNING: WireGuard does not seem to be running.${NC}"
		echo -e "${ORANGE}You can check if WireGuard is running with: systemctl status wg-quick@${SERVER_WG_NIC}${NC}"
		echo -e "${ORANGE}If you get something like \"Cannot find device ${SERVER_WG_NIC}\", please reboot!${NC}"
	else # WireGuard is running
		echo -e "\n${GREEN}WireGuard is running.${NC}"
		echo -e "${GREEN}You can check the status of WireGuard with: systemctl status wg-quick@${SERVER_WG_NIC}\n\n${NC}"
		echo -e "${ORANGE}If you don't have internet connectivity from your client, try to reboot the server.${NC}"
	fi
	warnAboutOtherFirewalls
}

function chooseEndpoint() {
	# Sets ENDPOINT to one of the server addresses saved at install time, or a custom host
	local OPTIONS=()
	local HOSTS=()
	local CHOICE=""
	local CUSTOM=""
	local INDEX

	if [[ -n ${SERVER_PUB_IPV6} ]]; then
		OPTIONS+=("IPv6 $(formatEndpoint "${SERVER_PUB_IPV6}" "${SERVER_PORT}") (recommended: IPv4 addresses attract most attacks)")
		HOSTS+=("${SERVER_PUB_IPV6}")
	fi
	if [[ -n ${SERVER_PUB_IPV4} ]]; then
		OPTIONS+=("IPv4 ${SERVER_PUB_IPV4}:${SERVER_PORT}")
		HOSTS+=("${SERVER_PUB_IPV4}")
	fi
	if [[ -n ${SERVER_HOSTNAME} ]]; then
		OPTIONS+=("Hostname ${SERVER_HOSTNAME}:${SERVER_PORT}")
		HOSTS+=("${SERVER_HOSTNAME}")
	fi
	OPTIONS+=("Another hostname or address")

	echo ""
	echo "Endpoint this client connects to (it must be able to reach it):"
	for INDEX in "${!OPTIONS[@]}"; do
		echo "   $((INDEX + 1))) ${OPTIONS[INDEX]}"
	done
	until [[ ${CHOICE} =~ ^[0-9]+$ && ${CHOICE} -ge 1 && ${CHOICE} -le ${#OPTIONS[@]} ]]; do
		read -rp "Select an option [1-${#OPTIONS[@]}]: " -e -i 1 CHOICE
	done

	if [[ ${CHOICE} -le ${#HOSTS[@]} ]]; then
		ENDPOINT=$(formatEndpoint "${HOSTS[CHOICE - 1]}" "${SERVER_PORT}")
	else
		until isValidIpv4 "${CUSTOM}" || isValidIpv6 "${CUSTOM}" || isValidHostname "${CUSTOM}"; do
			read -rp "Hostname or IP address: " -e CUSTOM
		done
		ENDPOINT=$(formatEndpoint "${CUSTOM}" "${SERVER_PORT}")
	fi
}

function readClientAddress() {
	# readClientAddress <variable> <prompt> <default> <ipv4|ipv6> <private|public>
	# Asks for an address until it is empty (unused), valid and not taken yet.
	local VARIABLE=$1
	local PROMPT=$2
	local DEFAULT=$3
	local FAMILY=$4
	local SCOPE=$5
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"
	local VALUE
	local PREFIX_LENGTH=32

	if [[ ${FAMILY} == ipv6 ]]; then
		PREFIX_LENGTH=128
	fi

	while :; do
		read -rp "${PROMPT} (leave empty if unused): " -e -i "${DEFAULT}" VALUE
		if [[ -z ${VALUE} ]]; then
			break
		fi

		if [[ ${FAMILY} == ipv4 ]] && ! isValidIpv4 "${VALUE}"; then
			echo -e "${ORANGE}${VALUE} is not a valid IPv4 address.${NC}"
		elif [[ ${FAMILY} == ipv6 ]] && ! isValidIpv6 "${VALUE}"; then
			echo -e "${ORANGE}${VALUE} is not a valid IPv6 address.${NC}"
		elif [[ ${VALUE} == "${SERVER_WG_IPV4}" || ${VALUE} == "${SERVER_WG_IPV6}" || ${VALUE} == "${SERVER_PUB_IPV4}" || ${VALUE} == "${SERVER_PUB_IPV6}" ]]; then
			echo -e "${ORANGE}${VALUE} is used by the server itself, please choose another address.${NC}"
		elif [[ ${SCOPE} == public ]] && [[ -n $(ip -o addr show to "${VALUE}" 2>/dev/null) ]]; then
			echo -e "${ORANGE}${VALUE} is configured on a network interface of this server, so it cannot be routed to a client.${NC}"
			echo -e "${ORANGE}Remove it from the network configuration (cloud-init, netplan, NetworkManager...) first.${NC}"
		elif grep -q -F "${VALUE}/${PREFIX_LENGTH}" "${WG_CONF_FILE}"; then
			echo -e "${ORANGE}A client with the address ${VALUE} was already created, please choose another one.${NC}"
		else
			break
		fi
		echo ""
	done

	printf -v "${VARIABLE}" '%s' "${VALUE}"
}

function newClient() {
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"

	echo ""
	echo "Client configuration"
	echo ""
	echo "The client name must consist of alphanumeric character(s). It may also include underscores or dashes and can't exceed 15 chars."

	until [[ ${CLIENT_NAME} =~ ^[a-zA-Z0-9_-]+$ && ${CLIENT_EXISTS} == '0' && ${#CLIENT_NAME} -lt 16 ]]; do
		read -rp "Client name: " -e CLIENT_NAME
		CLIENT_EXISTS=$(grep -c -E "^### Client ${CLIENT_NAME}\$" "${WG_CONF_FILE}")

		if [[ ${CLIENT_EXISTS} != 0 ]]; then
			echo ""
			echo -e "${ORANGE}A client with the specified name was already created, please choose another name.${NC}"
			echo ""
		fi
	done

	if [[ ${PUBLIC_ROUTING_MODE} == 'yes' ]]; then
		echo ""
		echo "A private client gets an address from the tunnel subnet and is NATed behind the server."
		echo "A public client gets one of the server's additional public addresses, routed without NAT."
		echo "A mixed client gets both."
		until [[ ${CLIENT_ADDRESS_MODE} =~ ^(private|public|mixed)$ ]]; do
			read -rp "Client address mode [private/public/mixed]: " -e -i private CLIENT_ADDRESS_MODE
		done
	else
		CLIENT_ADDRESS_MODE=private
	fi

	CLIENT_PRIVATE_IPV4=""
	CLIENT_PRIVATE_IPV6=""
	CLIENT_PUBLIC_IPV4=""
	CLIENT_PUBLIC_IPV6=""

	if [[ ${CLIENT_ADDRESS_MODE} != 'public' ]]; then
		BASE_IPV4=$(echo "${SERVER_WG_IPV4}" | awk -F '.' '{ print $1"."$2"."$3 }')
		BASE_IPV6=$(echo "${SERVER_WG_IPV6}" | awk -F '::' '{ print $1 }')

		# Pick the first free host address of the tunnel subnet
		for DOT_IP in {2..254}; do
			DOT_EXISTS=$(grep -c -F "${BASE_IPV4}.${DOT_IP}/32" "${WG_CONF_FILE}")
			if [[ ${DOT_EXISTS} == '0' ]]; then
				break
			fi
		done

		if [[ ${DOT_EXISTS} != '0' ]]; then
			echo ""
			echo "The subnet configured supports only 253 clients."
			exit 1
		fi

		readClientAddress CLIENT_PRIVATE_IPV4 "Private client IPv4" "${BASE_IPV4}.${DOT_IP}" ipv4 private
		readClientAddress CLIENT_PRIVATE_IPV6 "Private client IPv6" "${BASE_IPV6}::${DOT_IP}" ipv6 private
	fi

	if [[ ${CLIENT_ADDRESS_MODE} != 'private' ]]; then
		echo ""
		echo "Public addresses must be routed to this server by your provider (additional/failover IP)."
		readClientAddress CLIENT_PUBLIC_IPV4 "Public client IPv4" "" ipv4 public
		DEFAULT_PUBLIC_IPV6=""
		if [[ -n ${SERVER_PUB_IPV6_PREFIX} ]]; then
			mapfile -t USED_IPV6 < <({
				echo "${SERVER_PUB_IPV6}"
				listServerIpv6Addresses
				listPublicAddresses PublicIPv6 "$(getPeerBlocksFromConfig "${WG_CONF_FILE}")"
			} | grep -v '^$')
			DEFAULT_PUBLIC_IPV6=$(suggestPublicIpv6 "${SERVER_PUB_IPV6_PREFIX}" "${USED_IPV6[@]}")
		fi
		readClientAddress CLIENT_PUBLIC_IPV6 "Public client IPv6" "${DEFAULT_PUBLIC_IPV6}" ipv6 public
	fi

	if ! validateClientAddressMode \
		"${CLIENT_ADDRESS_MODE}" \
		"${CLIENT_PRIVATE_IPV4}" \
		"${CLIENT_PUBLIC_IPV4}" \
		"${CLIENT_PRIVATE_IPV6}" \
		"${CLIENT_PUBLIC_IPV6}"; then
		echo ""
		echo -e "${RED}The selected client address mode (${CLIENT_ADDRESS_MODE}) does not match the provided addresses.${NC}"
		exit 1
	fi

	chooseEndpoint

	# Generate key pair for the client
	CLIENT_PRIV_KEY=$(wg genkey)
	CLIENT_PUB_KEY=$(echo "${CLIENT_PRIV_KEY}" | wg pubkey)
	CLIENT_PRE_SHARED_KEY=$(wg genpsk)

	HOME_DIR=$(getHomeDirForClient "${CLIENT_NAME}")
	CLIENT_FILE="${HOME_DIR}/${SERVER_WG_NIC}-client-${CLIENT_NAME}.conf"

	# Create client file and add the server as a peer
	printf '%s\n' "$(buildClientConfig \
		"${SERVER_WG_MTU}" \
		"${CLIENT_PRIV_KEY}" \
		"${SERVER_PUB_KEY}" \
		"${CLIENT_PRE_SHARED_KEY}" \
		"${ENDPOINT}" \
		"${ALLOWED_IPS}" \
		"${CLIENT_DNS_1}" \
		"${CLIENT_DNS_2}" \
		"${CLIENT_PRIVATE_IPV4}" \
		"${CLIENT_PUBLIC_IPV4}" \
		"${CLIENT_PRIVATE_IPV6}" \
		"${CLIENT_PUBLIC_IPV6}")" >"${CLIENT_FILE}"
	chmod 600 "${CLIENT_FILE}"
	chown --reference="${HOME_DIR}" "${CLIENT_FILE}"

	# Add the client as a peer to the server
	NEW_PEER_BLOCK=$(buildServerPeerBlock \
		"${CLIENT_NAME}" \
		"${CLIENT_ADDRESS_MODE}" \
		"${CLIENT_PUB_KEY}" \
		"${CLIENT_PRE_SHARED_KEY}" \
		"${CLIENT_PRIVATE_IPV4}" \
		"${CLIENT_PUBLIC_IPV4}" \
		"${CLIENT_PRIVATE_IPV6}" \
		"${CLIENT_PUBLIC_IPV6}" \
		"${ENDPOINT}")
	EXISTING_PEER_BLOCKS=$(getPeerBlocksFromConfig "${WG_CONF_FILE}")

	if [[ -n ${EXISTING_PEER_BLOCKS} ]]; then
		PEER_BLOCKS="${EXISTING_PEER_BLOCKS}

${NEW_PEER_BLOCK}"
	else
		PEER_BLOCKS="${NEW_PEER_BLOCK}"
	fi

	applyServerConfig "${PEER_BLOCKS}"

	# Generate QR code if qrencode is installed
	if command -v qrencode &>/dev/null; then
		echo -e "${GREEN}\nHere is your client config file as a QR Code:\n${NC}"
		qrencode -t ansiutf8 -l L <"${CLIENT_FILE}"
		echo ""
	fi

	echo -e "${GREEN}Your client config file is in ${CLIENT_FILE}${NC}"
}

function formatAge() {
	# formatAge <epoch seconds> [now]: elapsed time of a handshake, "never" for 0
	local ELAPSED

	if [[ $1 -eq 0 ]]; then
		echo never
		return
	fi
	ELAPSED=$((${2:-$(date +%s)} - $1))
	if ((ELAPSED < 60)); then
		echo "${ELAPSED}s ago"
	elif ((ELAPSED < 3600)); then
		echo "$((ELAPSED / 60))min ago"
	elif ((ELAPSED < 86400)); then
		echo "$((ELAPSED / 3600))h ago"
	else
		echo "$((ELAPSED / 86400))d ago"
	fi
}

function formatBytes() {
	LC_ALL=C numfmt --to=iec-i --suffix=B "$1"
}

function listClientsFromConfig() {
	# listClientsFromConfig <config file>: "name|mode|public key|addresses|endpoint" per client
	# Addresses are listed like in the client configuration: public first, IPv4 first
	awk -F ': ' '
		/^### Client / { name = $0; sub(/^### Client /, "", name); mode = ""; endpoint = ""; split("", address) }
		/^# AddressMode: / { mode = $2 }
		/^# PublicIPv4: / { address[1] = $2 }
		/^# PrivateIPv4: / { address[2] = $2 }
		/^# PublicIPv6: / { address[3] = $2 }
		/^# PrivateIPv6: / { address[4] = $2 }
		/^# Endpoint: / { endpoint = $2 }
		/^PublicKey = / {
			addresses = ""
			for (i = 1; i <= 4; i++) if (address[i] != "") addresses = addresses (addresses != "" ? ", " : "") address[i]
			print name "|" mode "|" substr($0, 13) "|" addresses "|" endpoint
		}' "$1"
}

function showStatus() {
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"
	local PEER_BLOCKS
	local DUMP
	local NAME MODE KEY ADDRESSES ENDPOINT PEER_LINE SEEN_FROM HANDSHAKE TRAFFIC
	local FORMAT='%-15s %-8s %-42s %-26s %-24s %-11s %s\n'

	PEER_BLOCKS=$(getPeerBlocksFromConfig "${WG_CONF_FILE}")

	echo ""
	echo "Server"
	echo "  Interface       ${SERVER_WG_NIC} on ${SERVER_PUB_NIC}, UDP port ${SERVER_PORT}, MTU ${SERVER_WG_MTU}, $(systemctl is-active "wg-quick@${SERVER_WG_NIC}")"
	echo "  Endpoints       IPv4 ${SERVER_PUB_IPV4:-none}, IPv6 ${SERVER_PUB_IPV6:-none}, hostname ${SERVER_HOSTNAME:-none}"
	echo "  Public routing  ${PUBLIC_ROUTING_MODE}${SERVER_PUB_IPV6_PREFIX:+, IPv6 prefix ${SERVER_PUB_IPV6_PREFIX}}"
	echo "  Firewall        $(detectHostFirewall) detected, rules managed by the installer: ${FIREWALL_INTEGRATION}"
	if [[ ${PUBLIC_ROUTING_MODE} == yes ]]; then
		echo "  Announcements   $(systemctl is-active "wg-public-ipv4-announce@${SERVER_WG_NIC}") for: $(listPublicAddresses PublicIPv4 "${PEER_BLOCKS}" | paste -sd ' ')"
		echo "  Proxy entries   $({
			ip -4 neigh show proxy
			ip -6 neigh show proxy
		} 2>/dev/null | awk '{ print $1 }' | paste -sd ' ')"
	fi
	echo ""

	if [[ -z ${PEER_BLOCKS} ]]; then
		echo "No clients yet."
		return
	fi

	# shellcheck disable=SC2059
	printf "${FORMAT}" CLIENT MODE ADDRESSES "CONNECTS TO" "SEEN FROM" HANDSHAKE "RX / TX"
	DUMP=$(wg show "${SERVER_WG_NIC}" dump 2>/dev/null | tail -n +2)
	while IFS='|' read -r NAME MODE KEY ADDRESSES ENDPOINT; do
		PEER_LINE=$(grep -F "${KEY}" <<<"${DUMP}" | head -1)
		if [[ -n ${PEER_LINE} ]]; then
			SEEN_FROM=$(cut -f 3 <<<"${PEER_LINE}")
			HANDSHAKE=$(formatAge "$(cut -f 5 <<<"${PEER_LINE}")")
			TRAFFIC="$(formatBytes "$(cut -f 6 <<<"${PEER_LINE}")") / $(formatBytes "$(cut -f 7 <<<"${PEER_LINE}")")"
		else
			SEEN_FROM="-"
			HANDSHAKE="not loaded"
			TRAFFIC="-"
		fi
		# shellcheck disable=SC2059
		printf "${FORMAT}" "${NAME}" "${MODE}" "${ADDRESSES}" "${ENDPOINT}" "${SEEN_FROM}" "${HANDSHAKE}" "${TRAFFIC}"
	done < <(listClientsFromConfig "${WG_CONF_FILE}")
}

function revokeClient() {
	local WG_CONF_FILE="/etc/wireguard/${SERVER_WG_NIC}.conf"

	NUMBER_OF_CLIENTS=$(grep -c -E "^### Client" "${WG_CONF_FILE}")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		echo ""
		echo "You have no existing clients!"
		exit 1
	fi

	echo ""
	echo "Select the existing client you want to revoke"
	grep -E "^### Client" "${WG_CONF_FILE}" | cut -d ' ' -f 3 | nl -s ') '
	until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
		if [[ ${CLIENT_NUMBER} == '1' ]]; then
			read -rp "Select one client [1]: " CLIENT_NUMBER
		else
			read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
		fi
	done

	# match the selected number to a client name
	CLIENT_NAME=$(grep -E "^### Client" "${WG_CONF_FILE}" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)

	# remove generated client file
	HOME_DIR=$(getHomeDirForClient "${CLIENT_NAME}")
	rm -f "${HOME_DIR}/${SERVER_WG_NIC}-client-${CLIENT_NAME}.conf"

	# regenerate the server configuration without the [Peer] block of this client
	PEER_BLOCKS=$(getPeerBlocksFromConfig "${WG_CONF_FILE}" | sed "/^### Client ${CLIENT_NAME}\$/,/^$/d")
	applyServerConfig "${PEER_BLOCKS}"
}

function uninstallWg() {
	echo ""
	echo -e "\n${RED}WARNING: This will uninstall WireGuard and remove all the configuration files!${NC}"
	echo -e "${ORANGE}Please backup the /etc/wireguard directory if you want to keep your configuration files.\n${NC}"
	read -rp "Do you really want to remove WireGuard? [y/n]: " -e REMOVE
	REMOVE=${REMOVE:-n}
	if [[ $REMOVE == 'y' ]]; then
		removePublicIpv4AnnouncementService
		removeFirewallIntegration

		systemctl disable --now "wg-quick@${SERVER_WG_NIC}"
		nft delete table inet wireguard 2>/dev/null

		case "${OS_FAMILY}" in
		debian)
			apt-get -o DPkg::Lock::Timeout=300 remove -y wireguard wireguard-tools qrencode
			;;
		rhel)
			dnf remove -y --noautoremove wireguard-tools qrencode
			if [[ ${OS} != 'fedora' && ${VERSION_ID%%.*} == 8 ]]; then
				dnf remove -y --noautoremove kmod-wireguard
			fi
			;;
		arch)
			local PACKAGE
			for PACKAGE in wireguard-tools qrencode; do
				if pacman -Qi "${PACKAGE}" &>/dev/null; then
					pacman -Rs --noconfirm "${PACKAGE}"
				fi
			done
			;;
		suse)
			zypper --non-interactive remove wireguard-tools qrencode
			;;
		flatcar)
			# Flatcar ships WireGuard in its read-only /usr, nothing to remove
			;;
		esac

		rm -rf /etc/wireguard
		rm -f /etc/sysctl.d/wg.conf

		# Removing the file does not unset anything, so the routing-only value is reset by hand
		if [[ ${PUBLIC_ROUTING_MODE} == 'yes' ]]; then
			sysctl -q -w net.ipv6.conf.all.proxy_ndp=0
		fi

		# Check if WireGuard is running
		systemctl is-active --quiet "wg-quick@${SERVER_WG_NIC}"
		WG_RUNNING=$?

		if [[ ${WG_RUNNING} -eq 0 ]]; then
			echo "WireGuard failed to uninstall properly."
			exit 1
		else
			echo "WireGuard uninstalled successfully."
			exit 0
		fi
	else
		echo ""
		echo "Removal aborted!"
	fi
}

function loadParams() {
	source /etc/wireguard/params

	# Installations made by earlier versions lack these keys
	SERVER_WG_MTU=${SERVER_WG_MTU:-1420}
	FIREWALL_INTEGRATION=${FIREWALL_INTEGRATION:-none}
	SERVER_PUB_IPV4=${SERVER_PUB_IPV4:-}
	SERVER_PUB_IPV6=${SERVER_PUB_IPV6:-}
	SERVER_HOSTNAME=${SERVER_HOSTNAME:-}
	SERVER_PUB_IPV6_PREFIX=${SERVER_PUB_IPV6_PREFIX:-}
	if [[ -n ${SERVER_PUB_IP:-} && -z ${SERVER_PUB_IPV4}${SERVER_PUB_IPV6}${SERVER_HOSTNAME} ]]; then
		local LEGACY_ENDPOINT=${SERVER_PUB_IP//[\[\]]/}
		if isValidIpv4 "${LEGACY_ENDPOINT}"; then
			SERVER_PUB_IPV4=${LEGACY_ENDPOINT}
		elif isValidIpv6 "${LEGACY_ENDPOINT}"; then
			SERVER_PUB_IPV6=${LEGACY_ENDPOINT}
		else
			SERVER_HOSTNAME=${LEGACY_ENDPOINT}
		fi
	fi
}

function manageMenu() {
	echo "Welcome to WireGuard-install!"
	echo "The git repository is available at: https://github.com/tbringuier/wireguard-install"
	echo ""
	echo "It looks like WireGuard is already installed."
	echo ""
	echo "What do you want to do?"
	echo "   1) Add a new client"
	echo "   2) Show clients and status"
	echo "   3) Revoke a client"
	echo "   4) Uninstall WireGuard"
	echo "   5) Exit"
	until [[ ${MENU_OPTION} =~ ^[1-5]$ ]]; do
		read -rp "Select an option [1-5]: " MENU_OPTION
	done
	case "${MENU_OPTION}" in
	1)
		newClient
		;;
	2)
		showStatus
		;;
	3)
		revokeClient
		;;
	4)
		uninstallWg
		;;
	5)
		exit 0
		;;
	esac
}

if [[ "${WG_INSTALL_TESTING:-0}" != 1 ]]; then
	# Check for root, virt, OS...
	initialCheck

	# Check if WireGuard is already installed and load params
	if [[ -e /etc/wireguard/params ]]; then
		loadParams
		manageMenu
	else
		installWireGuard
	fi
fi
